CREATE TABLE t1 (id INTEGER PRIMARY KEY);
CREATE TABLE t2 (id INTEGER PRIMARY KEY, t1_id INTEGER);
CREATE TABLE t3 (id INTEGER PRIMARY KEY, t2_id INTEGER, val TEXT);
INSERT INTO t1 VALUES (1), (2);
INSERT INTO t2 VALUES (10, 1), (20, 2);
INSERT INTO t3 VALUES (100, 10, 'a'), (200, 20, 'b');
SELECT t1.id, t2.id, t3.val FROM t1 INNER JOIN t2 ON t1.id = t2.t1_id INNER JOIN t3 ON t2.id = t3.t2_id ORDER BY t3.val;