[package]
name = "sqlrustgo-tools"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sqlrustgo-catalog.workspace = true
sqlrustgo-storage.workspace = true
sqlrustgo-types.workspace = true
anyhow.workspace = true
rand = "0.8"
log.workspace = true
env_logger.workspace = true
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
parking_lot.workspace = true
structopt = "0.3"
regex = "1.0"
flate2 = "1.0"
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
tempfile = "3.0"

[[bin]]
name = "tbl2bin"
path = "src/bin/tbl2bin.rs"

[[bin]]
name = "bench_client"
path = "src/bin/bench_client.rs"

[[bin]]
name = "physical-backup"
path = "src/bin/physical_backup.rs"
