[package]
name = "sqlrustgo-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
log.workspace = true
anyhow.workspace = true
async-trait.workspace = true
chrono = "0.4"
flate2 = "1.0"
lz4_flex = "0.11"
zstd = "0.13"

[dev-dependencies]
tempfile.workspace = true
