#!/usr/bin/env python3
"""
Verification Engine - Anti-Cheat Proof Generator

Core principle: Proof is GENERATED by CI, not declared by PR.
This script reads test execution results and generates a verification report.
"""

import json
import subprocess
import re
import sys
import os


def run_tests():
    """Run full test suite and capture results."""
    result = subprocess.run(
        ["cargo", "test"],
        capture_output=True,
        text=True,
        cwd=os.environ.get("CARGO_TESTS_DIR", ".")
    )
    return result.returncode, result.stdout + result.stderr


def parse_results(output):
    """Parse cargo test output to extract pass/fail counts."""
    passed = 0
    failed = 0

    for line in output.splitlines():
        if "test result:" in line:
            # Example: "test result: ok. 12 passed; 0 failed; 0 ignored; ..."
            m = re.search(r'(\d+) passed; (\d+) failed', line)
            if m:
                passed += int(m.group(1))
                failed += int(m.group(2))

    return passed, failed


def generate_report():
    """Generate verification report from test execution."""
    code, output = run_tests()
    passed, failed = parse_results(output)

    report = {
        "proof_version": "1.0",
        "generated_by": "verification_engine.py",
        "source": "CI execution (not PR declaration)",
        "passed": passed,
        "failed": failed,
        "baseline_verified": failed == 0 and code == 0,
        "blocker_count": failed,
        "status": "VERIFIED" if (failed == 0 and code == 0) else "FAIL"
    }

    # Write report to file (generated by CI, not PR)
    with open("verification_report.json", "w") as f:
        json.dump(report, f, indent=2)

    print("=" * 50)
    print("VERIFICATION REPORT")
    print("=" * 50)
    print(json.dumps(report, indent=2))
    print("=" * 50)

    if failed > 0 or code != 0:
        print(f"❌ VERIFICATION FAILED: {failed} test(s) failed")
        sys.exit(1)
    else:
        print(f"✅ VERIFICATION PASSED: {passed} tests passed")
        sys.exit(0)


if __name__ == "__main__":
    generate_report()
