#!/usr/bin/env python3
"""Generate TPC-H baseline hash from tests/tpch_full_22_test output.

Runs the 22-query TPC-H test, parses the per-query row counts from
`✅ Q1: N rows` summary lines, reorders to Q1..Q22, computes SHA-256.

The hash is a "row-count baseline" — simpler than the original row-data
hash (tpch_hash_compare.py parses `---rows---` blocks which tpch_full_22_test
does not emit), but still catches regressions in the number of rows
returned per query.

Output: writes a 64-char hex hash to stdout (for piping into the
tests/tpch_hashes_v380.json baseline file).

Usage:
    python3 scripts/gate/tpch_baseline_hash.py [--baseline-out PATH]
"""

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_BASELINE = REPO_ROOT / "tests" / "tpch_hashes_v380.json"

# tpch_full_22_test prints: `✅ Q1: 4 rows in 3.06ms` (or ⏱ / ❌)
SUMMARY_RE = re.compile(r"^\s*(?:✅|⏱|❌)\s*Q(\d+):\s+(\d+)\s+rows", re.MULTILINE)


def run_test() -> str:
    """Run cargo test --test tpch_full_22_test and return captured stdout."""
    proc = subprocess.run(
        ["cargo", "test", "--test", "tpch_full_22_test", "--", "--nocapture", "--test-threads=1"],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        timeout=1800,
    )
    return (proc.stdout or "") + "\n" + (proc.stderr or "")


def parse_row_counts(output: str) -> dict[int, int]:
    """Parse `✅ Q1: N rows` lines into {Q_num: row_count}."""
    counts: dict[int, int] = {}
    for m in SUMMARY_RE.finditer(output):
        q = int(m.group(1))
        n = int(m.group(2))
        if 1 <= q <= 22 and q not in counts:
            counts[q] = n
    return counts


def hash_from_counts(counts: dict[int, int]) -> str:
    """Compute SHA-256 of `Q1=N1\\nQ2=N2\\n...Q22=N22\\n` (canonical order)."""
    buf: list[str] = []
    for q in range(1, 23):
        n = counts.get(q, 0)
        buf.append(f"Q{q}={n}")
    body = ("\n".join(buf) + "\n").encode("utf-8")
    return hashlib.sha256(body).hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate TPC-H baseline hash (row-count based)")
    ap.add_argument("--baseline-out", type=Path, default=DEFAULT_BASELINE,
                    help=f"Where to write the JSON (default: {DEFAULT_BASELINE})")
    ap.add_argument("--stdout", action="store_true",
                    help="Print just the 64-char hash to stdout (skip writing JSON)")
    args = ap.parse_args()

    print("[hash] Running tpch_full_22_test...", file=sys.stderr)
    output = run_test()
    counts = parse_row_counts(output)

    if len(counts) != 22:
        print(f"ERROR: expected 22 Q-summary lines, got {len(counts)}:", file=sys.stderr)
        for q in range(1, 23):
            marker = "✓" if q in counts else "✗"
            print(f"  {marker} Q{q}: {counts.get(q, 'MISSING')}", file=sys.stderr)
        print("\nLast 30 lines of test output:", file=sys.stderr)
        for line in output.splitlines()[-30:]:
            print(f"  | {line}", file=sys.stderr)
        return 1

    h = hash_from_counts(counts)
    print(f"[hash] 22 query counts captured, hash = {h}", file=sys.stderr)

    if args.stdout:
        print(h)
        return 0

    baseline = {
        "_meta": {
            "version": "v3.9.0-rc7",
            "generated_at": "2026-06-17",
            "generator": "scripts/gate/tpch_baseline_hash.py",
            "algorithm": "SHA-256 of `Q1=N1\\n...Q22=N22\\n` (row-count baseline)",
            "data": "tests/data/tpch-sf001/ (SF=0.001, generated by scripts/gate/generate_sf001_fixture.py)",
            "rows": {f"Q{q}": counts[q] for q in range(1, 23)},
        },
        "tpc_h_hash_sha256": h,
    }
    args.baseline_out.parent.mkdir(parents=True, exist_ok=True)
    args.baseline_out.write_text(json.dumps(baseline, indent=2, ensure_ascii=False) + "\n")
    print(f"[hash] Wrote {args.baseline_out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
